[server]
fileWatcherType = "none"
headless = true
enableCORS = false
port = $PORT

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
