[server]
fileWatcherType = "none"
headless = true
enableCORS = false
port = 8501  # <--- Use a valid integer here

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
